// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // `prisma migrate` needs a direct (non-pooled) connection to hold its
    // advisory lock — Neon's pooled DATABASE_URL times out on that. The app
    // itself still connects via the pooled URL at runtime (see lib/prisma.ts).
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
